# Bot Configuration
bot:
  prefix: "!"
  status: "Albion Analytics"
  log_level: "INFO"

# Guild Settings (Example for initialization)
guilds:
  - name: "Take a Break"
    code: "TAB123"
    founder_code: "FOUNDARTAB_UIO123" 
    mentor_code: "MENTORTAB_UIO942"
  
  - name: "AltMetal"
    code: "AM456"
    founder_code: "FOUNDERAM_XYZ789"
    mentor_code: "MENTORAM_ABC123"

# Discord Roles (IDs)
roles:
  member_id: 1434197939068342302
  mentor_id: 1471208796507603076
  founder_id: 1431094365706649691
